export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";