export default [
  {
    path:"/",
    title:"首页",
    icon:"home"
  },
  {
    title:"商品",
    icon:"appstore",
    path:"/products",
    children:[
      {
        path:"/category",
        title:"分类管理",
        icon:"bars"
      },
      {
        path:"/product",
        title:"商品管理",
        icon:"tool"
      },
    ]
  },
  {
    path:"/user",
    title:"用户管理",
    icon:"user"
  },
  {
    path:"/role",
    title:"权限管理",
    icon:"safety-certificate"
  },
  {
    title:"图形图表",
    icon:"area-chart",
    path:"/charts",
    children:[
      {
        path:"/charts/bar",
        title:"柱状图",
        icon:"bar-chart"
      },
      {
        path:"/charts/line",
        title:"折线图",
        icon:"line-chart"
      },
      {
        path:"/charts/pie",
        title:"饼状图",
        icon:"pie-chart"
      },
    ]
  },
]